ALTER TABLE training_programs
  ADD COLUMN IF NOT EXISTS breadcrumb_label TEXT,
  ADD COLUMN IF NOT EXISTS category_label TEXT,
  ADD COLUMN IF NOT EXISTS mode_label TEXT,
  ADD COLUMN IF NOT EXISTS duration_label TEXT,
  ADD COLUMN IF NOT EXISTS fee_sub_label TEXT,
  ADD COLUMN IF NOT EXISTS registration_deadline TEXT,
  ADD COLUMN IF NOT EXISTS outcomes TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS audience TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS contact_email TEXT,
  ADD COLUMN IF NOT EXISTS contact_phone TEXT;

UPDATE training_programs
SET
  breadcrumb_label = COALESCE(breadcrumb_label, 'Agribusiness Development'),
  category_label = COALESCE(category_label, 'Agribusiness'),
  mode_label = COALESCE(mode_label, 'Hybrid'),
  duration_label = COALESCE(duration_label, '5 Days'),
  fee_sub_label = COALESCE(fee_sub_label, 'per participant · incl. materials & lunch'),
  registration_deadline = COALESCE(registration_deadline, '20 March 2025'),
  outcomes = CASE WHEN cardinality(outcomes) = 0 THEN ARRAY[
    'Identify key market access barriers for smallholder farmers in North-Central Nigeria',
    'Develop a structured agribusiness plan using the Value Chain Canvas framework',
    'Apply pricing, costing, and margin analysis to agricultural enterprises',
    'Connect with buyers, cooperatives, and off-taker networks through structured networking',
    'Navigate formal and informal financing options including cooperative credit schemes'
  ] ELSE outcomes END,
  audience = CASE WHEN cardinality(audience) = 0 THEN ARRAY[
    'Smallholder farmers',
    'Agro-processors',
    'Cooperative officers',
    'Extension agents',
    'Rural entrepreneurs'
  ] ELSE audience END,
  contact_email = COALESCE(contact_email, 'training@tcoefs.unijos.edu.ng'),
  contact_phone = COALESCE(contact_phone, '+234 (0) 803 XXX XXXX')
WHERE slug = 'agribusiness-development-market-access';

UPDATE training_programs
SET
  breadcrumb_label = COALESCE(breadcrumb_label, 'Crop Production'),
  category_label = COALESCE(category_label, 'Crop Science'),
  mode_label = COALESCE(mode_label, 'On-site'),
  duration_label = COALESCE(duration_label, '5 Days'),
  fee_sub_label = COALESCE(fee_sub_label, 'per participant · incl. field materials & lunch'),
  registration_deadline = COALESCE(registration_deadline, '5 March 2025'),
  outcomes = CASE WHEN cardinality(outcomes) = 0 THEN ARRAY[
    'Apply integrated soil fertility management strategies to improve crop yields',
    'Select appropriate varieties and seed systems for North-Central agroecologies',
    'Design a practical integrated pest and disease management plan',
    'Implement post-harvest handling procedures to reduce loss at farm level',
    'Operate and maintain small-scale grain storage structures correctly'
  ] ELSE outcomes END,
  audience = CASE WHEN cardinality(audience) = 0 THEN ARRAY[
    'Smallholder farmers',
    'Extension officers',
    'Agronomists',
    'Seed system practitioners',
    'NGO field staff'
  ] ELSE audience END,
  contact_email = COALESCE(contact_email, 'training@tcoefs.unijos.edu.ng'),
  contact_phone = COALESCE(contact_phone, '+234 (0) 803 XXX XXXX')
WHERE slug = 'sustainable-crop-production';

UPDATE training_programs
SET
  breadcrumb_label = COALESCE(breadcrumb_label, 'Food Safety & HACCP'),
  category_label = COALESCE(category_label, 'Food Processing'),
  mode_label = COALESCE(mode_label, 'Online'),
  duration_label = COALESCE(duration_label, '5 Days'),
  fee_sub_label = COALESCE(fee_sub_label, 'per participant · incl. course materials'),
  registration_deadline = COALESCE(registration_deadline, '2 April 2025'),
  outcomes = CASE WHEN cardinality(outcomes) = 0 THEN ARRAY[
    'Map food safety risks across processing workflows',
    'Build a practical HACCP plan for a food enterprise',
    'Interpret core NAFDAC-aligned compliance requirements',
    'Strengthen batch traceability and quality control procedures',
    'Prepare internal staff for safer plant operations'
  ] ELSE outcomes END,
  audience = CASE WHEN cardinality(audience) = 0 THEN ARRAY[
    'Food processors',
    'Quality officers',
    'Extension agents',
    'SME founders',
    'Factory supervisors'
  ] ELSE audience END,
  contact_email = COALESCE(contact_email, 'training@tcoefs.unijos.edu.ng'),
  contact_phone = COALESCE(contact_phone, '+234 (0) 803 XXX XXXX')
WHERE slug = 'food-safety-standards-haccp';

UPDATE training_programs
SET
  breadcrumb_label = COALESCE(breadcrumb_label, 'Climate-Smart Agriculture'),
  category_label = COALESCE(category_label, 'Climate'),
  mode_label = COALESCE(mode_label, 'On-site'),
  duration_label = COALESCE(duration_label, '5 Days'),
  fee_sub_label = COALESCE(fee_sub_label, 'per participant · incl. materials & lunch'),
  registration_deadline = COALESCE(registration_deadline, '17 April 2025'),
  outcomes = CASE WHEN cardinality(outcomes) = 0 THEN ARRAY[
    'Assess climate risks across local farming systems',
    'Apply resilient water, soil, and cropping practices',
    'Integrate adaptation planning into farm operations',
    'Use climate information for production decisions',
    'Build action plans for sustainable field implementation'
  ] ELSE outcomes END,
  audience = CASE WHEN cardinality(audience) = 0 THEN ARRAY[
    'Farm managers',
    'Extension workers',
    'Researchers',
    'Climate project staff',
    'Producers'
  ] ELSE audience END,
  contact_email = COALESCE(contact_email, 'training@tcoefs.unijos.edu.ng'),
  contact_phone = COALESCE(contact_phone, '+234 (0) 803 XXX XXXX')
WHERE slug = 'climate-smart-agriculture';

UPDATE training_programs
SET
  breadcrumb_label = COALESCE(breadcrumb_label, 'Irrigation Management'),
  category_label = COALESCE(category_label, 'Agribusiness'),
  mode_label = COALESCE(mode_label, 'On-site'),
  duration_label = COALESCE(duration_label, '5 Days'),
  fee_sub_label = COALESCE(fee_sub_label, 'per participant · incl. materials & lunch'),
  registration_deadline = COALESCE(registration_deadline, '1 May 2025'),
  outcomes = CASE WHEN cardinality(outcomes) = 0 THEN ARRAY[
    'Plan efficient irrigation schedules for farm systems',
    'Reduce field-level water loss through better practices',
    'Maintain small and medium irrigation infrastructure',
    'Compare irrigation options for different value chains',
    'Track water productivity against farm output goals'
  ] ELSE outcomes END,
  audience = CASE WHEN cardinality(audience) = 0 THEN ARRAY[
    'Farm operators',
    'Irrigation technicians',
    'Extension officers',
    'Project managers',
    'Water user groups'
  ] ELSE audience END,
  contact_email = COALESCE(contact_email, 'training@tcoefs.unijos.edu.ng'),
  contact_phone = COALESCE(contact_phone, '+234 (0) 803 XXX XXXX')
WHERE slug = 'irrigation-management-water-conservation';

CREATE TABLE IF NOT EXISTS postgraduate_programmes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  deadline TEXT NOT NULL,
  start_date TEXT NOT NULL,
  mode TEXT NOT NULL,
  duration TEXT NOT NULL,
  fees NUMERIC(10, 2) NOT NULL DEFAULT 0,
  overview TEXT NOT NULL,
  outcomes TEXT[] NOT NULL DEFAULT '{}',
  eligibility TEXT NOT NULL,
  required_documents TEXT[] NOT NULL DEFAULT '{}',
  institution TEXT,
  awarding_body TEXT,
  qualifications TEXT[] NOT NULL DEFAULT '{}',
  pgd_duration TEXT,
  msc_duration TEXT,
  programme_objectives TEXT[] NOT NULL DEFAULT '{}',
  core_modules TEXT[] NOT NULL DEFAULT '{}',
  pgd_admission_requirements TEXT,
  msc_admission_requirements TEXT,
  registration_info TEXT,
  career_outcomes TEXT[] NOT NULL DEFAULT '{}',
  keywords TEXT[] NOT NULL DEFAULT '{}',
  creator_id UUID NOT NULL REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT postgraduate_programmes_slug_format CHECK (slug ~ '^[a-z0-9-]+$'),
  CONSTRAINT postgraduate_programmes_fees_positive CHECK (fees >= 0),
  CONSTRAINT postgraduate_programmes_status_check CHECK (status IN ('draft', 'published', 'closing_soon', 'closed'))
);

CREATE INDEX IF NOT EXISTS idx_postgraduate_programmes_status
  ON postgraduate_programmes(status);

ALTER TABLE postgraduate_programmes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS postgraduate_programmes_select_all ON postgraduate_programmes;
CREATE POLICY postgraduate_programmes_select_all ON postgraduate_programmes
  FOR SELECT USING (true);

INSERT INTO postgraduate_programmes (
  title,
  slug,
  code,
  status,
  deadline,
  start_date,
  mode,
  duration,
  fees,
  overview,
  outcomes,
  eligibility,
  required_documents,
  institution,
  awarding_body,
  qualifications,
  pgd_duration,
  msc_duration,
  programme_objectives,
  core_modules,
  pgd_admission_requirements,
  msc_admission_requirements,
  registration_info,
  career_outcomes,
  keywords,
  creator_id
)
SELECT
  seed.title,
  seed.slug,
  seed.code,
  seed.status,
  seed.deadline,
  seed.start_date,
  seed.mode,
  seed.duration,
  seed.fees,
  seed.overview,
  seed.outcomes,
  seed.eligibility,
  seed.required_documents,
  seed.institution,
  seed.awarding_body,
  seed.qualifications,
  seed.pgd_duration,
  seed.msc_duration,
  seed.programme_objectives,
  seed.core_modules,
  seed.pgd_admission_requirements,
  seed.msc_admission_requirements,
  seed.registration_info,
  seed.career_outcomes,
  seed.keywords,
  users.id
FROM (
  VALUES
    (
      'Climate Change & Sustainable Food Security',
      'climate-change-sustainable-food-security',
      'CCFS 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; on-campus with field-based components',
      'One academic year (full-time); two years (part-time)',
      0,
      'This programme provides rigorous, interdisciplinary training at the intersection of climate science and food systems. Students examine how shifting climatic patterns, extreme weather events, and environmental degradation threaten agricultural productivity and rural livelihoods across Sub-Saharan Africa and beyond. The curriculum integrates climate modelling, agronomic adaptation strategies, policy analysis, and food systems governance to equip graduates with tools for evidence-based decision-making in an era of accelerating environmental change.',
      ARRAY['Understand the mechanisms and projected impacts of climate change on agricultural systems and food supply chains.', 'Develop and evaluate climate adaptation and mitigation strategies tailored to smallholder and commercial farming contexts.', 'Apply quantitative and qualitative research methods to assess food security vulnerabilities at community, national, and regional scales.', 'Design and implement resilient food system interventions informed by international frameworks such as the Paris Agreement and the Sustainable Development Goals.', 'Engage constructively with policy processes, development agencies, and rural stakeholders on climate-food nexus issues.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD)', 'Master of Science (MSc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Understand the mechanisms and projected impacts of climate change on agricultural systems and food supply chains.', 'Develop and evaluate climate adaptation and mitigation strategies tailored to smallholder and commercial farming contexts.', 'Apply quantitative and qualitative research methods to assess food security vulnerabilities at community, national, and regional scales.', 'Design and implement resilient food system interventions informed by international frameworks such as the Paris Agreement and the Sustainable Development Goals.', 'Engage constructively with policy processes, development agencies, and rural stakeholders on climate-food nexus issues.'],
      ARRAY['Foundations of Climate Science and Agricultural Systems', 'Food Security Frameworks: Concepts, Measurement, and Policy', 'Climate-Smart Agriculture and Agroecology', 'Remote Sensing and GIS for Food Security Analysis', 'Climate Finance and Green Economy', 'Research Methods in Agricultural and Environmental Sciences', 'Dissertation / Applied Research Project (MSc only)'],
      'A recognised BSc Bachelor''s degree (minimum Second Class Lower) in Agriculture, Environmental Science, Geography, Economics, or a related discipline; or relevant professional experience.',
      'A PGD in a related area or a Bachelor''s degree (minimum Second Class Lower) in a relevant field; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Climate and food security analyst in government ministries and international organisations', 'Programme officer in NGOs, UN agencies (FAO, WFP, UNDP), and development banks', 'Agricultural policy researcher and consultant', 'Academic/researcher in universities and think tanks', 'Environmental impact assessment specialist'],
      ARRAY['climate change', 'food security', 'sustainable agriculture', 'adaptation', 'policy']
    ),
    (
      'Disaster Risk Management in Agriculture & Food Security',
      'disaster-risk-management-agriculture-food-security',
      'DRM 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; on-campus with field-based components',
      'One academic year (full-time); two years (part-time)',
      0,
      'Disasters, both natural and human-induced, represent one of the gravest threats to agricultural output and household food security in Africa. This programme equips students with the theoretical foundations and practical competencies to assess, reduce, and manage disaster risks within agricultural and food system contexts. Drawing on hazard analysis, vulnerability mapping, early warning systems, and humanitarian response protocols, graduates are positioned to lead disaster preparedness and recovery initiatives at community, national, and international levels.',
      ARRAY['Analyse the causes, dynamics, and consequences of agricultural and food-related disasters including droughts, floods, pest outbreaks, and conflict-induced crises.', 'Apply the Sendai Framework for Disaster Risk Reduction and related international protocols to agricultural and food security planning.', 'Develop community-based disaster risk reduction strategies with particular attention to vulnerable and marginalised populations.', 'Use geospatial tools, early warning systems, and data analytics for disaster monitoring and risk forecasting.', 'Design post-disaster recovery and livelihood restoration programmes for farming communities.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD)', 'Master of Science (MSc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Analyse the causes, dynamics, and consequences of agricultural and food-related disasters including droughts, floods, pest outbreaks, and conflict-induced crises.', 'Apply the Sendai Framework for Disaster Risk Reduction and related international protocols to agricultural and food security planning.', 'Develop community-based disaster risk reduction strategies with particular attention to vulnerable and marginalised populations.', 'Use geospatial tools, early warning systems, and data analytics for disaster monitoring and risk forecasting.', 'Design post-disaster recovery and livelihood restoration programmes for farming communities.'],
      ARRAY['Introduction to Disaster Risk Reduction (DRR) and Management', 'Hazard, Vulnerability, and Capacity Assessment in Agriculture', 'Early Warning Systems and Agricultural Intelligence', 'Humanitarian Logistics and Emergency Food Response', 'Climate Extremes and Agricultural Disaster Linkages', 'Policy and Governance for Agricultural DRM', 'Applied Research / Dissertation (MSc only)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Agriculture, Geography, Environmental Management, Social Sciences, or a related discipline.',
      'A PGD in a related area or a Bachelor''s degree (minimum Second Class Lower) in a relevant field; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Disaster risk reduction officer in government emergency management agencies', 'Humanitarian aid coordinator with WFP, ICRC, and related organisations', 'Resilience programme manager in NGOs and development institutions', 'Agricultural risk analyst for insurance companies and development banks', 'Researcher in disaster studies, climate adaptation, and food systems'],
      ARRAY['disaster risk', 'food security', 'DRR', 'humanitarian', 'Sendai Framework']
    ),
    (
      'Gender, Agriculture & Rural Development',
      'gender-agriculture-rural-development',
      'GAR 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; on-campus with field-based components',
      'One academic year (full-time); two years (part-time)',
      0,
      'Women constitute the majority of smallholder farmers across Sub-Saharan Africa yet continue to face profound inequalities in access to land, credit, inputs, extension services, and decision-making power. This programme critically examines the gendered dimensions of agricultural systems and rural development, integrating feminist theory, development economics, and participatory research methods. Graduates develop the analytical and practical competencies to design and evaluate gender-responsive agricultural interventions, policies, and programmes.',
      ARRAY['Critically analyse gender dynamics within agricultural value chains, rural institutions, and food systems.', 'Apply gender analysis frameworks and tools to programme design, monitoring, and evaluation in agricultural and rural development contexts.', 'Examine policy and legal frameworks governing women''s land rights, access to finance, and market participation in Nigeria and across Africa.', 'Engage with rural communities using participatory approaches to co-design gender-transformative interventions.', 'Contribute to evidence-based gender mainstreaming in agricultural development practice.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD-GAR)', 'Master of Science (MSc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Critically analyse gender dynamics within agricultural value chains, rural institutions, and food systems.', 'Apply gender analysis frameworks and tools to programme design, monitoring, and evaluation in agricultural and rural development contexts.', 'Examine policy and legal frameworks governing women''s land rights, access to finance, and market participation in Nigeria and across Africa.', 'Engage with rural communities using participatory approaches to co-design gender-transformative interventions.', 'Contribute to evidence-based gender mainstreaming in agricultural development practice.'],
      ARRAY['Gender Theory and Development Practice', 'Women in Agriculture: Roles, Constraints, and Opportunities', 'Rural Sociology and Community Development', 'Gender-Responsive Policy Analysis', 'Participatory Research Methods', 'Agricultural Finance and Women''s Economic Empowerment', 'Applied Research / Dissertation (MSc only)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Social Sciences, Agriculture, Development Studies, or a related discipline.',
      'A PGD-GAR or a relevant Bachelor''s degree with research experience; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Gender specialist in development organisations, NGOs, and UN agencies', 'Agricultural extension officer with a gender mandate', 'Policy analyst and researcher in women, land, and food security', 'Programme coordinator for rural development and livelihood projects', 'Academic and researcher in gender studies and development economics'],
      ARRAY['gender', 'rural development', 'women empowerment', 'agriculture', 'participatory research']
    ),
    (
      'Agricultural Economics and Food Systems Innovation',
      'agricultural-economics-food-systems-innovation',
      'AEF 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time',
      '18 months to two years (full-time); up to three years (part-time)',
      0,
      'This advanced postgraduate programme bridges economic theory and practical food systems analysis to address the complex challenges of agricultural development in Africa. Students explore market structures, production economics, value chain dynamics, trade policy, and the economics of innovation in food and agriculture. With a strong emphasis on quantitative methods, data analytics, and applied research, graduates are equipped for careers in research, policy, and the growing agri-food private sector.',
      ARRAY['Apply microeconomic and macroeconomic theories to the analysis of agricultural markets, firms, and households.', 'Use advanced econometric methods and data analytics tools to evaluate agricultural policies, programmes, and market interventions.', 'Analyse food value chains from production through processing and retail to identify efficiency gaps and innovation opportunities.', 'Examine trade policy, food price dynamics, and the political economy of food systems governance.', 'Conduct original empirical research contributing to the evidence base for agricultural transformation in Nigeria and Africa.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Master of Science (M.Sc)'],
      NULL,
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Apply microeconomic and macroeconomic theories to the analysis of agricultural markets, firms, and households.', 'Use advanced econometric methods and data analytics tools to evaluate agricultural policies, programmes, and market interventions.', 'Analyse food value chains from production through processing and retail to identify efficiency gaps and innovation opportunities.', 'Examine trade policy, food price dynamics, and the political economy of food systems governance.', 'Conduct original empirical research contributing to the evidence base for agricultural transformation in Nigeria and Africa.'],
      ARRAY['Agricultural Production Economics and Farm Management', 'Food Systems Analysis and Value Chain Development', 'Advanced Agricultural Policy and Trade', 'Quantitative Methods and Econometrics for Agricultural Research', 'Agricultural Finance and Rural Credit Markets', 'Innovation Economics and Agri-Tech Adoption', 'Research Methods and Dissertation'],
      NULL,
      'A Bachelor''s degree (minimum Second Class Lower) in Economics, Agricultural Economics, Statistics, or a related quantitative discipline. Applicants with relevant professional experience in agricultural or food system roles may also be considered.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Agricultural economist in government, international organisations, and development banks', 'Food systems analyst and policy consultant', 'Research fellow in agricultural economics institutions', 'Market analyst and value chain development specialist in the agri-food private sector', 'Academic researcher and lecturer in economics and agricultural sciences'],
      ARRAY['agricultural economics', 'food systems', 'econometrics', 'policy', 'value chains']
    ),
    (
      'Master of Business Administration (MBA) in Agribusiness',
      'mba-agribusiness',
      'MBA 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time',
      'Typically 18 months to two years (full-time); part-time option available',
      0,
      'The MBA in Agribusiness prepares future leaders for the business of agriculture and food. Combining a rigorous foundation in management disciplines with specialised modules in agricultural value chains, agri-finance, and food enterprise development, this programme is designed for professionals seeking to drive commercial transformation in Nigeria''s agri-food sector. Students develop strategic thinking, entrepreneurial skills, and sector-specific knowledge required to build, manage, and scale agribusiness enterprises in a competitive and rapidly evolving landscape.',
      ARRAY['Develop advanced managerial and leadership competencies applicable to agribusiness enterprises and food industry organisations.', 'Analyse agribusiness value chains and identify commercial opportunities for productivity enhancement, market access, and profitability.', 'Apply financial management, investment analysis, and risk assessment tools to agribusiness contexts.', 'Design, evaluate, and implement strategies for agri-enterprise growth, including digital transformation and market expansion.', 'Demonstrate ethical, inclusive, and sustainable business leadership within the food and agricultural sector.'],
      'Minimum BSc (Second Class Lower) in any discipline.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports', 'Minimum two years of relevant work experience'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Master of Business Administration (MBA)'],
      NULL,
      'Typically 18 months to two years (full-time); part-time option available',
      ARRAY['Develop advanced managerial and leadership competencies applicable to agribusiness enterprises and food industry organisations.', 'Analyse agribusiness value chains and identify commercial opportunities for productivity enhancement, market access, and profitability.', 'Apply financial management, investment analysis, and risk assessment tools to agribusiness contexts.', 'Design, evaluate, and implement strategies for agri-enterprise growth, including digital transformation and market expansion.', 'Demonstrate ethical, inclusive, and sustainable business leadership within the food and agricultural sector.'],
      ARRAY['Foundations of Agribusiness Management', 'Financial Management for Agricultural Enterprises', 'Agricultural Marketing and Supply Chain Management', 'Agri-Tech and Digital Transformation in Food Systems', 'Entrepreneurship and New Venture Creation in Agriculture', 'Strategic Management and Business Planning', 'Agribusiness Project (Applied Capstone)'],
      NULL,
      'A recognised Bachelor''s degree (minimum Second Class Lower) in any discipline. A minimum of two years of relevant work experience is strongly preferred. GMAT or equivalent aptitude assessment may be required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Agribusiness entrepreneur and food enterprise owner', 'Senior manager in food processing, agro-industry, and agricultural supply chains', 'Agricultural investment analyst in commercial banks and development finance institutions', 'Business development officer in agri-cooperatives and farmer organisations', 'Agri-sector consultant and strategic advisor'],
      ARRAY['MBA', 'agribusiness', 'food enterprise', 'management', 'entrepreneurship']
    ),
    (
      'Agricultural Communication Innovations',
      'agricultural-communication-innovations',
      'ACI 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time',
      'One academic year (full-time); two years (part-time)',
      0,
      'Effective communication is a linchpin of agricultural transformation. This programme explores the theory and practice of agricultural communication, extension services, and knowledge management in the context of a rapidly digitalising world. Students examine how information and communication technologies, social media, radio broadcasting, and participatory media can be harnessed to close knowledge gaps between researchers, extension agents, and farmers. Graduates are prepared to lead innovative communication campaigns and knowledge-sharing initiatives that drive adoption of improved agricultural practices.',
      ARRAY['Analyse communication theories and their application in agricultural knowledge transfer and behaviour change.', 'Design and implement evidence-based agricultural extension programmes using traditional and digital media.', 'Evaluate the effectiveness of communication campaigns in promoting adoption of improved agricultural technologies.', 'Use digital tools, mobile platforms, and social media strategically for agricultural outreach and rural community engagement.', 'Develop science communication skills to translate complex research findings for diverse audiences including policymakers, farmers, and the media.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD)', 'Master of Science (M.Sc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Analyse communication theories and their application in agricultural knowledge transfer and behaviour change.', 'Design and implement evidence-based agricultural extension programmes using traditional and digital media.', 'Evaluate the effectiveness of communication campaigns in promoting adoption of improved agricultural technologies.', 'Use digital tools, mobile platforms, and social media strategically for agricultural outreach and rural community engagement.', 'Develop science communication skills to translate complex research findings for diverse audiences including policymakers, farmers, and the media.'],
      ARRAY['Communication Theory and Agricultural Knowledge Systems', 'Agricultural Extension and Rural Advisory Services', 'Digital Communication and Social Media for Agriculture', 'Radio and Community Broadcasting for Smallholder Farmers', 'Science Communication and Science Journalism', 'Behaviour Change Communication in Food Security', 'Applied Research / Dissertation (MSc only)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Mass Communication, Agriculture, Extension, or a related field.',
      'A PGD in a related area or a Bachelor''s degree (minimum Second Class Lower) in a relevant field; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Agricultural communication and extension specialist', 'Knowledge management officer in research institutes and development organisations', 'Digital media producer for agricultural campaigns and outreach', 'Science communicator and agricultural journalist', 'Programme officer in organisations implementing farmer advisory and outreach services'],
      ARRAY['agricultural communication', 'extension', 'digital media', 'knowledge transfer', 'outreach']
    ),
    (
      'Livestock Science and Climate Resilience',
      'livestock-science-climate-resilience',
      'LSC 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; on-campus with field-based components',
      'One academic year (full-time); two years (part-time)',
      0,
      'Livestock production systems across Africa are under mounting pressure from climate variability, land degradation, disease outbreaks, and market uncertainties. This programme equips students with advanced knowledge of livestock physiology, rangeland ecology, and climate adaptation strategies to sustain and improve the productivity and resilience of animal-based food systems. It bridges the biological sciences with climate science and development practice to prepare graduates who can design, implement, and evaluate climate-smart livestock strategies.',
      ARRAY['Understand the physiological, nutritional, and genetic determinants of livestock productivity under variable climatic conditions.', 'Assess the vulnerability of livestock systems to climate change impacts including heat stress, drought, and shifting disease burdens.', 'Apply rangeland management, silvopastoral, and agro-pastoral strategies to enhance climate resilience in livestock systems.', 'Analyse livestock-climate policy frameworks and their implications for food security and rural livelihoods.', 'Conduct applied research on climate adaptation strategies for cattle, goats, sheep, and poultry production systems.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD)', 'Master of Science (MSc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Understand the physiological, nutritional, and genetic determinants of livestock productivity under variable climatic conditions.', 'Assess the vulnerability of livestock systems to climate change impacts including heat stress, drought, and shifting disease burdens.', 'Apply rangeland management, silvopastoral, and agro-pastoral strategies to enhance climate resilience in livestock systems.', 'Analyse livestock-climate policy frameworks and their implications for food security and rural livelihoods.', 'Conduct applied research on climate adaptation strategies for cattle, goats, sheep, and poultry production systems.'],
      ARRAY['Livestock Physiology and Nutrition', 'Climate Change Impacts on Livestock Systems', 'Rangeland and Pasture Management', 'Climate-Smart Livestock Production Technologies', 'Livestock Disease Epidemiology and Climate Linkages', 'Livestock Policy, Markets, and Value Chains', 'Applied Research / Dissertation (MSc only)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Animal Science, Veterinary Medicine, Agriculture, or a related discipline.',
      'A PGD in a related area or a Bachelor''s degree (minimum Second Class Lower) in a relevant field; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Livestock production and climate adaptation specialist', 'Range and pasture management officer', 'Animal health and productivity researcher', 'Agri-policy analyst specialising in livestock systems', 'Programme specialist in FAO, ILRI, and international livestock development organisations'],
      ARRAY['livestock', 'climate resilience', 'animal science', 'rangeland', 'food security']
    ),
    (
      'Livestock Production and Animal Health',
      'livestock-production-animal-health',
      'LPA 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; on-campus and laboratory-based components',
      'One academic year (full-time); two years (part-time)',
      0,
      'This programme provides comprehensive training in the science of livestock production and animal health management, with an emphasis on improving productivity, reducing disease burden, and ensuring food safety across the livestock value chain. Students develop practical and research-based competencies in feed and nutrition management, breeding and genetics, veterinary epidemiology, and the One Health framework linking animal, human, and environmental health. The programme prepares graduates for roles in industry, government veterinary services, research, and international development.',
      ARRAY['Apply advanced knowledge of animal nutrition, genetics, and reproduction to improve the productivity of livestock enterprises.', 'Diagnose, prevent, and control major livestock diseases affecting cattle, small ruminants, and poultry in Nigeria and the West African region.', 'Implement biosecurity protocols and food safety standards across livestock production and processing systems.', 'Use the One Health framework to address zoonotic diseases and antimicrobial resistance at the animal-human-environment interface.', 'Manage livestock enterprises efficiently, integrating animal welfare, market demands, and sustainability considerations.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD)', 'Master of Science (MSc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Apply advanced knowledge of animal nutrition, genetics, and reproduction to improve the productivity of livestock enterprises.', 'Diagnose, prevent, and control major livestock diseases affecting cattle, small ruminants, and poultry in Nigeria and the West African region.', 'Implement biosecurity protocols and food safety standards across livestock production and processing systems.', 'Use the One Health framework to address zoonotic diseases and antimicrobial resistance at the animal-human-environment interface.', 'Manage livestock enterprises efficiently, integrating animal welfare, market demands, and sustainability considerations.'],
      ARRAY['Animal Nutrition and Feed Management', 'Livestock Breeding, Genetics, and Reproductive Management', 'Veterinary Epidemiology and Disease Control', 'Poultry, Ruminant, and Swine Production Systems', 'One Health: Zoonoses, Antimicrobial Resistance, and Food Safety', 'Livestock Enterprise Management and Marketing', 'Applied Research / Dissertation (MSc only)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Animal Science, Veterinary Medicine, Agriculture, or a related discipline.',
      'A PGD in a related area or a Bachelor''s degree (minimum Second Class Lower) in a relevant field; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Livestock production manager on commercial and smallholder farms', 'Animal health officer in government veterinary agencies', 'Agri-business specialist in feed manufacturing and veterinary pharmaceuticals', 'Food safety inspector and quality assurance officer', 'Researcher in animal science and veterinary public health'],
      ARRAY['livestock production', 'animal health', 'veterinary', 'One Health', 'food safety']
    ),
    (
      'Crop Protection',
      'crop-protection',
      'CP 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; on-campus and laboratory-based components',
      'One academic year (full-time); two years (part-time)',
      0,
      'Crop losses due to pests, diseases, and weeds remain a major constraint to food security across Nigeria and the broader African continent, accounting for pre- and post-harvest losses estimated at 30 to 40 percent of total production annually. This programme equips students with advanced knowledge of entomology, plant pathology, weed science, and integrated pest management (IPM) to protect crops and sustain agricultural productivity. The curriculum balances biological, chemical, and cultural control strategies with an emphasis on environmental sustainability, food safety, and farmer-centred innovation.',
      ARRAY['Identify and characterise major crop pests, diseases, and weeds affecting key food crops in Nigeria and West Africa.', 'Design and implement integrated pest management (IPM) programmes appropriate for smallholder and large-scale farming systems.', 'Evaluate the efficacy, safety, and environmental impact of biological, chemical, and cultural pest control strategies.', 'Apply pesticide regulations, resistance management protocols, and safe use guidelines in field and advisory contexts.', 'Conduct research on emerging pest and disease threats, including climate-driven range shifts of crop pathogens and vectors.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Postgraduate Diploma (PGD)', 'Master of Science (MSc)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time)',
      ARRAY['Identify and characterise major crop pests, diseases, and weeds affecting key food crops in Nigeria and West Africa.', 'Design and implement integrated pest management (IPM) programmes appropriate for smallholder and large-scale farming systems.', 'Evaluate the efficacy, safety, and environmental impact of biological, chemical, and cultural pest control strategies.', 'Apply pesticide regulations, resistance management protocols, and safe use guidelines in field and advisory contexts.', 'Conduct research on emerging pest and disease threats, including climate-driven range shifts of crop pathogens and vectors.'],
      ARRAY['Principles of Entomology and Pest Management', 'Plant Pathology: Diseases of Field and Horticultural Crops', 'Weed Science and Herbicide Management', 'Integrated Pest Management (IPM) Systems', 'Biopesticides and Biological Control Methods', 'Pesticide Science: Chemistry, Regulation, and Resistance', 'Applied Research / Dissertation (MSc only)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Agriculture, Botany, Zoology, Biochemistry, or a related field.',
      'A PGD in crop protection or a closely related area, or a relevant Bachelor''s degree (minimum Second Class Lower); a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Crop protection officer in government agricultural agencies and extension services', 'Agrochemical industry specialist in pesticide development, registration, and sales', 'IPM consultant and agricultural advisory services provider', 'Plant quarantine and biosecurity officer', 'Research scientist in agricultural entomology, plant pathology, or weed science'],
      ARRAY['crop protection', 'IPM', 'plant pathology', 'entomology', 'food security']
    ),
    (
      'Seed Science and Technology',
      'seed-science-technology',
      'SST 501',
      'published',
      '30 September 2025',
      'October 2025',
      'Full-time and part-time; laboratory-intensive',
      'One academic year (full-time); two years (part-time)',
      0,
      'Seeds are the fundamental unit of agricultural productivity. Improved seed systems, seed quality assurance, and seed technology innovation are essential drivers of food security and agricultural transformation. This programme provides advanced training in seed biology, seed production systems, seed testing methodologies, and the legal and regulatory frameworks governing the seed industry in Nigeria and internationally. Graduates contribute to building robust seed systems that support smallholder farmers, national breeding programmes, and the commercial seed sector.',
      ARRAY['Understand the biology of seed development, germination, dormancy, and vigour in major food and horticultural crops.', 'Design and manage seed production, conditioning, processing, and storage systems under varying agro-ecological conditions.', 'Apply national and international seed testing and certification protocols including ISTA and NASC standards.', 'Evaluate genetic and physiological seed quality parameters and implement quality assurance systems across the seed value chain.', 'Analyse seed policy, intellectual property rights, and access and benefit-sharing frameworks governing plant genetic resources.'],
      'Minimum BSc (Second Class Lower) in a relevant field.',
      ARRAY['Degree certificate', 'Official transcript', 'NYSC discharge/exemption', 'Statement of purpose', 'Two referee reports'],
      'University of Jos, Nigeria',
      'University of Jos (through TCoEFS)',
      ARRAY['Master of Agriculture (M.Agric)', 'Postgraduate Diploma (PGD)'],
      'One academic year (full-time); two years (part-time)',
      '18 months to two years (full-time); up to three years (part-time) – conferred as M.Agric',
      ARRAY['Understand the biology of seed development, germination, dormancy, and vigour in major food and horticultural crops.', 'Design and manage seed production, conditioning, processing, and storage systems under varying agro-ecological conditions.', 'Apply national and international seed testing and certification protocols including ISTA and NASC standards.', 'Evaluate genetic and physiological seed quality parameters and implement quality assurance systems across the seed value chain.', 'Analyse seed policy, intellectual property rights, and access and benefit-sharing frameworks governing plant genetic resources.'],
      ARRAY['Seed Biology: Development, Dormancy, and Germination', 'Seed Production and Crop Improvement', 'Seed Processing, Conditioning, and Storage Technology', 'Seed Quality Testing and Certification', 'Seed Systems and Seed Policy in Africa', 'Plant Genetic Resources and Intellectual Property', 'Applied Research / Dissertation / Project (M.Agric)'],
      'A recognised Bachelor''s degree (minimum Second Class Lower) in Agriculture, Agronomy, Botany, Plant Biology, or a related discipline.',
      'A PGD in seed science or a closely related area, or a Bachelor''s degree (minimum Second Class Lower) in a relevant field; a statement of research interest is required.',
      'Applications and registration are currently processed through the University of Jos central admissions portal. Prospective students are advised to visit the University of Jos official website for application deadlines, portal access, and required documentation.',
      ARRAY['Seed production manager on commercial and government seed farms', 'Seed quality control and certification officer with NASC and state seed councils', 'Plant breeder and variety development specialist', 'Seed industry analyst and agribusiness development officer', 'Researcher in seed science, genetics, and plant biotechnology'],
      ARRAY['seed science', 'seed technology', 'plant breeding', 'seed systems', 'food security']
    )
) AS seed(title, slug, code, status, deadline, start_date, mode, duration, fees, overview, outcomes, eligibility, required_documents, institution, awarding_body, qualifications, pgd_duration, msc_duration, programme_objectives, core_modules, pgd_admission_requirements, msc_admission_requirements, registration_info, career_outcomes, keywords)
CROSS JOIN LATERAL (
  SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1
) AS users
WHERE NOT EXISTS (
  SELECT 1 FROM postgraduate_programmes existing WHERE existing.slug = seed.slug
);